# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXQd-3NsLRNee-58LC2JI3yXywVSBWtI
"""

a = input()
def good_number(s) -> str:
    n = '\\1234567890'
    m = ''
    for i in s:
        if i in n:
            m += i
        else:
            m += ' '
    m = m.split()
    for i in range(len(m)):
        if m[i][1] == '\\':
            m[i] = '000' + m[i]
            if len(m[i]) == 6:
                m[i] = m[i][:5] + '0000' + m[i][-1:]
            if len(m[i]) == 7:
                m[i] = m[i][:5] + '000' + m[i][-2:]
            if len(m[i]) == 8:
                m[i] = m[i][:5] + '00' + m[i][-3:]
            if len(m[i]) == 9:
                m[i] = m[i][:5] + '0' + m[i][-4:]
        elif m[i][2] == '\\':
            m[i] = '00' + m[i]
            if len(m[i]) == 6:
                m[i] = m[i][:5] + '0000' + m[i][-1:]
            if len(m[i]) == 7:
                m[i] = m[i][:5] + '000' + m[i][-2:]
            if len(m[i]) == 8:
                m[i] = m[i][:5] + '00' + m[i][-3:]
            if len(m[i]) == 9:
                m[i] = m[i][:5] + '0' + m[i][-4:]
        elif m[i][3] == '\\':
            m[i] = '0' + m[i]
            if len(m[i]) == 6:
                m[i] = m[i][:5] + '0000' + m[i][-1:]
            if len(m[i]) == 7:
                m[i] = m[i][:5] + '000' + m[i][-2:]
            if len(m[i]) == 8:
                m[i] = m[i][:5] + '00' + m[i][-3:]
            if len(m[i]) == 9:
                m[i] = m[i][:5] + '0' + m[i][-4:]
    print(*m, sep = '\n')
good_number(a)